  QUESTIONS NAME : --> 
    
    
    1) COUNT DIGITS
    2) PALINDROME NUMBER
    3) FACTORIAL OF A NUMBER
    4) GCD OF TWO NIUMBERS 
    5) HCF OD TWO NUMBERS
    6) CHECK FOR PRIME
    7) PRIME FACTORS
    8) SIEVE OF ERATHOSTHENES
    9) COMPUTING POWERS
    
